CREATE TABLE category (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID))ENGINE=InnoDB DEFAULT  CHARSET=utf8;

  INSERT INTO category(DESCRIPTION) VALUES ('Lazer');
  INSERT INTO category(DESCRIPTION) VALUES ('Alimentação');
  INSERT INTO category(DESCRIPTION) VALUES ('Supermercado');
  INSERT INTO category(DESCRIPTION) VALUES ('Farmácia');
  INSERT INTO category(DESCRIPTION) VALUES ('Outros');