CREATE TABLE entry (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	DESCRIPTION VARCHAR(50) NOT NULL COMMENT 'Descricao do lancamento',
	VALUE_DATE DATE NOT NULL COMMENT 'Data do vencimento',
	DUE_DATE DATE COMMENT 'Data do pagamento',
	VALUE DECIMAL(10,2) NOT NULL COMMENT 'Valor do lancamento',
	OBSERVATION VARCHAR(100) COMMENT 'Observacao',
	TYPE VARCHAR(20) NOT NULL COMMENT 'Tipo de lancamento',
	ID_CATEGORY BIGINT(20) NOT NULL COMMENT 'Codigo da categoria',
	ID_PERSON BIGINT(20) NOT NULL COMMENT 'Codigo da Pessoa'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE entry ADD INDEX FK_ENTRY_PERSON_idx (ID_PERSON ASC) VISIBLE;
ALTER TABLE entry
    ADD CONSTRAINT FK_ENTRY_PERSON
        FOREIGN KEY (ID_PERSON)
            REFERENCES person (ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;

ALTER TABLE entry ADD INDEX FK_ENTRY_CATEGORY_idx (ID_CATEGORY ASC) VISIBLE;
ALTER TABLE entry
ADD CONSTRAINT FK_ENTRY_CATEGORY
  FOREIGN KEY (ID_CATEGORY)
  REFERENCES category (ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Salário mensal', '2017-06-10', null, 6500.00, 'Distribuição de lucros', 'RECEITA', 1, 1);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Bahamas', '2017-02-10', '2017-02-10', 100.32, null, 'DESPESA', 2, 2);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Top Club', '2017-06-10', null, 120, null, 'RECEITA', 3, 3);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('CEMIG', '2017-02-10', '2017-02-10', 110.44, 'Geração', 'RECEITA', 3, 4);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('DMAE', '2017-06-10', null, 200.30, null, 'DESPESA', 3, 5);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Extra', '2017-03-10', '2017-03-10', 1010.32, null, 'RECEITA', 4, 6);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Bahamas', '2017-06-10', null, 500, null, 'RECEITA', 1, 7);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Top Club', '2017-03-10', '2017-03-10', 400.32, null, 'DESPESA', 4, 8);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Despachante', '2017-06-10', null, 123.64, 'Multas', 'DESPESA', 3, 9);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Pneus', '2017-04-10', '2017-04-10', 665.33, null, 'RECEITA', 5, 10);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Café', '2017-06-10', null, 8.32, null, 'DESPESA', 1, 5);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Eletrônicos', '2017-04-10', '2017-04-10', 2100.32, null, 'DESPESA', 5, 4);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Instrumentos', '2017-06-10', null, 1040.32, null, 'DESPESA', 4, 3);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Café', '2017-04-10', '2017-04-10', 4.32, null, 'DESPESA', 4, 2);
INSERT INTO entry (DESCRIPTION, VALUE_DATE, DUE_DATE, VALUE, OBSERVATION, TYPE, ID_CATEGORY, ID_PERSON) values ('Lanche', '2017-06-10', null, 10.20, null, 'DESPESA', 4, 1);