CREATE TABLE USER (
	ID BIGINT(20) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(150) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


INSERT INTO USER (ID, NAME, EMAIL, PASSWORD) VALUES (1, 'Administrador', 'admin@money.com', '$2a$10$X607ZPhQ4EgGNaYKt3n4SONjIv9zc.VMWdEuhCuba7oLAL5IvcL5.');
INSERT INTO USER (ID, NAME, EMAIL, PASSWORD) VALUES (2, 'Maria Silva', 'maria@algamoney.com', '$2a$10$Zc3w6HyuPOPXamaMhh.PQOXvDnEsadztbfi6/RyZWJDzimE8WQjaq');
