CREATE TABLE PERMISSION (
	ID BIGINT(20) PRIMARY KEY,
	DESCRIPTION VARCHAR(50) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


INSERT INTO PERMISSION (ID, DESCRIPTION) VALUES (1, 'ROLE_REGISTER_CATEGORY');
INSERT INTO PERMISSION (ID, DESCRIPTION) VALUES (2, 'ROLE_PESQUISAR_CATEGORY');

INSERT INTO PERMISSION (ID, DESCRIPTION) VALUES (3, 'ROLE_REGISTER_PERSON');
INSERT INTO PERMISSION (ID, DESCRIPTION) VALUES (4, 'ROLE_REMOVER_PERSON');
INSERT INTO PERMISSION (ID, DESCRIPTION) VALUES (5, 'ROLE_SEARCH_PERSON');

INSERT INTO PERMISSION (ID, DESCRIPTION) VALUES (6, 'ROLE_REGISTER_ENTRY');
INSERT INTO PERMISSION (ID, DESCRIPTION) VALUES (7, 'ROLE_REMOVE_ENTRY');
INSERT INTO PERMISSION (ID, DESCRIPTION) VALUES (8, 'ROLE_SEARCH_ENTRY');