CREATE TABLE USER_PERMISSION (
	ID_USER BIGINT(20) NOT NULL,
	ID_PERMISSION BIGINT(20) NOT NULL,
	PRIMARY KEY (ID_USER, ID_PERMISSION),
	FOREIGN KEY (ID_USER) REFERENCES USER(ID),
	FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSION(ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


-- admin
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (1, 1);
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (1, 2);
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (1, 3);
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (1, 4);
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (1, 5);
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (1, 6);
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (1, 7);
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (1, 8);

-- maria
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (2, 2);
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (2, 5);
INSERT INTO USER_PERMISSION (ID_USER, ID_PERMISSION) values (2, 8);